CREATE USER IF NOT EXISTS 'auth_user'@'%' IDENTIFIED BY 'root';
GRANT ALL PRIVILEGES ON userdetails.* TO 'auth_user'@'%';

CREATE DATABASE IF NOT EXISTS userdetails;
CREATE DATABASE IF NOT EXISTS customerdb;
CREATE DATABASE IF NOT EXISTS accountsdb;
CREATE DATABASE IF NOT EXISTS transactiondb;

FLUSH PRIVILEGES;