version: '3.8'

services:

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userdetails
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d   # ✅ init.sql runs on first boot
      - mysql-data:/var/lib/mysql
    networks:
      - banking-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
      

  discovery-server:
    image: discovery-server:v1
    build: ./discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    networks:
      - banking-network

  api-gateway:
    image: api-gateway:v1
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8085:8085"
    depends_on:
      discovery-server:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - banking-network

  auth-service:
    image: auth-service:v1
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8083:8083"
    depends_on:
      mysql:
        condition: service_healthy
      discovery-server:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - banking-network

  customer-service:
    image: customer-service:v1
    build: ./customer-service
    container_name: customer-service
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      discovery-server:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - banking-network

  account-service:
    image: account-service:v1
    build: ./accounts-service
    container_name: accounts-service
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
      discovery-server:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - banking-network

  transactiondetails-service:
    image: transaction-details:v1
    build: ./transactiondetails-service
    container_name: transactiondetails-service
    ports:
      - "8082:8082"
    depends_on:
      mysql:
        condition: service_healthy
      discovery-server:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - banking-network

networks:
  banking-network:
    driver: bridge

volumes:
  mysql-data: