pipeline {

    agent any

    tools {
        jdk 'JDK17'
        maven 'Maven3'
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                url: 'https://github.com/shyamtalagapu/banking-microservices-system.git'
            }
        }

        stage('Verify Java') {
            steps {
                bat 'java -version'
            }
        }

        stage('Verify Maven') {
            steps {
                bat 'mvn -version'
            }
        }

        stage('Build Microservices') {
            steps {
                bat 'mvn clean install'
            }
        }
        stage('Veriy Docker'){
             steps {
                bat 'docker --version'
            }
        }
        stage('Build Docker Image for Auth Service'){
             steps {
                bat 'docker build -t auth-service:v1 .'
            }
        }

    }
}