pipeline {

    agent any

    tools {
        jdk 'JDK17'
        maven 'Maven3'
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                url: 'https://github.com/shyamtalagapu/banking-microservices-system.git'
            }
        }

        stage('Verify Java') {
            steps {
                bat 'java -version'
            }
        }

        stage('Verify Maven') {
            steps {
                bat 'mvn -version'
            }
        }

        stage('Build Microservices') {
            steps {
                bat 'mvn clean install'
            }
        }
        stage('Verify Docker'){
             steps {
                bat 'docker --version'
            }
        }
		stage('Clean Existing Containers') {
	    steps {
	        bat 'docker-compose down || exit 0'
	    }
		}
		stage('Build Containers and deploy banking microservices'){
		    steps{
		        bat 'docker compose up -d'
		    }
		}
    }
}