# ===============================
# SERVER
# ===============================
server.port=${PORT:8761}

spring.application.name=discovery-server

# ===============================
# EUREKA SERVER CONFIG
# ===============================
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Disable self-preservation warnings during local dev
eureka.server.enable-self-preservation=true