# ===============================
# SERVER
# ===============================
server.port=${PORT:8761}

spring.application.name=discovery-server

# ===============================
# EUREKA SERVER CONFIG
# ===============================
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Add to ALL services' application-docker.properties
eureka.client.initial-instance-info-replication-interval-seconds=10
eureka.client.registry-fetch-interval-seconds=10
spring.cloud.discovery.retry.max-attempts=10
spring.cloud.discovery.retry.initial-interval=3000

# Disable self-preservation warnings during local dev
eureka.server.enable-self-preservation=true